//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModernWebSampleApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DayOfBirth { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public System.DateTime AvailableSince { get; set; }
        public Nullable<System.DateTime> AvailableUntil { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
